# Generated by Django 4.2.7 on 2023-11-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(default="defaul.png", upload_to="category_icon/"),
        ),
    ]
