# Generated by Django 4.2.7 on 2023-11-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                default="category_icon/default.png", upload_to="category_icon/"
            ),
        ),
    ]
