# Generated by Django 4.2.7 on 2023-12-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tabletype')),
            ],
        ),
    ]
