# Generated by Django 4.2.7 on 2023-12-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_type',
        ),
        migrations.DeleteModel(
            name='TableType',
        ),
    ]
