# Generated by Django 4.2.7 on 2024-04-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_table_reserved_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='reserved_for',
        ),
    ]
