# Generated by Django 4.2.7 on 2023-11-30 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_canceled_order_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="item_price",
        ),
    ]
