# Generated by Django 4.2.7 on 2023-12-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_table_delete_table_delete_tabletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='canceled',
            new_name='is_active',
        ),
    ]
